services:
  oskari:
    build: ..
    # volumes:
     # - "./log:/log"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgis/postgis:17-3.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=supersalainen_oskarin_salasana
      - POSTGRES_USER=oskari
      - POSTGRES_DB=oskari
    volumes:
      - "./data:/var/lib/postgresql/data"
      - "./pg-initscripts/:/docker-entrypoint-initdb.d/:ro"
